---
- name: create grafna directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ grafana_uid }}"
    group: "{{ grafana_uid }}"
  with_items:
    - "{{ grafana_conf_dir }}"
    - "{{ grafana_data_dir }}"

- name: include setup_container.yml
  include_tasks: setup_container.yml

- name: include configure_grafana.yml
  include_tasks: configure_grafana.yml
