---
- name: include_tasks systemd.yml
  include_tasks: systemd.yml

- name: start the grafana-server service
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    daemon_reload: yes
  failed_when: false
