# [NOTE-zw] we ditched the container engine provisioning steps, to make sure the side effect is under control,
# the determination logic is simplified
---
- name: install container binding
  package:
    name: python3-docker
    update_cache: true
  register: result
  until: result is succeeded
  tags: with_pkg

- name: install lvm2 package
  package:
    name: lvm2
  register: result
  until: result is succeeded
  tags: with_pkg
  when: inventory_hostname in groups.get(osd_group_name, [])
